### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by krasnovpro** [jesterKing/import_3dm#22]
When I try to import 3dm, the Blender throws error:

Traceback (most recent call last):
  File "C:\usr\img\Blender\2.80\scripts\addons_contrib\import_3dm\__init__.py", line 81, in execute
    return read_3dm(context, self.filepath, self.import_hidden)
  File "C:\usr\img\Blender\2.80\scripts\addons_contrib\import_3dm\read3dm.py", line 43, in read_3dm
    converters.handle_layers(context, model, toplayer, layerids, materials)
  File "C:\usr\img\Blender\2.80\scripts\addons_contrib\import_3dm\converters\layers.py", line 48, in handle_layers
    principled.base_color = (r/255.0, g/255.0, b/255.0)
  File "C:\usr\img\Blender\2.80\scripts\modules\bpy_extras\node_shader_utils.py", line 37, in wrapper
    return func(self, *args, **kwargs)
  File "C:\usr\img\Blender\2.80\scripts\modules\bpy_extras\node_shader_utils.py", line 271, in base_color_set
    self.material.diffuse_color = color
ValueError: bpy_struct: item.attr = val: sequences of dimension 0 should contain 4 items, not 3

location: <unknown location>:-1

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Blender 2.80 latest.

**Comment by jesterKing** [comment]
Probably the color representation changed.

**Comment by jesterKing** [comment]
As a quick fix you could change

`principled.base_color = (r/255.0, g/255.0, b/255.0)`

to

`principled.base_color = (r/255.0, g/255.0, b/255.0, 1.0) # or 0.0, I forgot which way this is`

**Comment by jesterKing** [comment]
Apparently it was a bug in whatever version you had. I revisited this with Blender 2.80 69b2f5268114 (2019.02.11) and no change was necessary.
