### ISSUE TITLE
Addon doesn't activate on macOS & Blender 2.80

### ISSUE THREAD

**Issue by Oxervision** [jesterKing/import_3dm#23]
**Describe the bug**
When I try to install the addon it appears a error message

**To Reproduce**
1. Go to 'Preferences'
2. Click on 'Install' and select the .zip file downloaded
3. Click on checkbox to activate the addon
4. See error:
Traceback (most recent call last):
  File "/Applications/Blender/BLENDER 2.80/blender.app/Contents/Resources/2.80/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/Oxer/Library/Application Support/Blender/2.80/scripts/addons/rhino3dm/__init__.py", line 45, in <module>
    from .read3dm import read_3dm
  File "/Users/Oxer/Library/Application Support/Blender/2.80/scripts/addons/rhino3dm/read3dm.py", line 26, in <module>
    from . import converters
  File "/Users/Oxer/Library/Application Support/Blender/2.80/scripts/addons/rhino3dm/converters/__init__.py", line 35, in <module>
    r3d.ObjectType.Brep : import_render_mesh,
AttributeError: module 'rhino3dm' has no attribute 'ObjectType'

 - OS: macOs 10.13.6
 - Blender 2.80.44

**Comment by jesterKing** [comment]
@Oxervision the package is called import_3dm, not rhino3dm. The latter you are supposed to install using pip3.7 (so you need python3.7 installed on your osx well), then copy the rhino3dm module to the location where you have Blender installed.

So I first have python3.7 installed, then use

`pip3.7 -U --user rhino3dm`

I have it installed under /Applications, so I copy the rhino3dm module to `/Applications/blender.app/Contents/Resources/2.80/python/lib/python3.7/site-packages/` with: `cp -r /Users/nathan/Library/Python/3.7/lib/python/site-packages/rhino3dm /Applications/blender.app/Contents/Resources/2.80/python/lib/python3.7/site-packages/`

After that you can start Blender and install the import_3dm.zip through the add-ons section.

**Comment by Oxervision** [comment]
Ok, thanks for the info

**Comment by jesterKing** [comment]
Does this make it work for you?

**Comment by Oxervision** [comment]
**1.** How do I know that python3.7 is isntalled in my osx?
**2.** How to use "pip3.7 -U --user rhino3dm"? Is this a Terminal isntruction?
**3.** Where do I obtain the rhino3dm module?

**Comment by Oxervision** [comment]
I have installed python 3.7.2 right now, then I typed `pip3.7 -U --user rhino3dm` in the Terminal and it appears this:

```
Usage:   
  pip3.7 <command> [options]

no such option: -U
```
What do I do now?

**Comment by Oxervision** [comment]
I downloaded the Python 3.7 installer and I installed Python 3.7 but the path to the installation is different to your, python3.7 installed in:

/Library/Frameworks/Python.framework

**Comment by jesterKing** [comment]
Sorry, I typoed. The command is `pip3.7 install -U --user rhino3dm`

**Comment by Oxervision** [comment]
It works now!!  After install python 3.7 the correct command to install rhino3dm was:

`pip3.7 install rhino3dm `

![addon import 3dm](https://user-images.githubusercontent.com/46649474/52881291-78854000-3164-11e9-9159-55265069aea3.jpg)

**Comment by jesterKing** [comment]
Yay. Thanks for reporting and walking through the process. I'll add these as install instructions for OS X.

**Comment by Oxervision** [comment]
Ok, if you want that I test the new addon versions on macos, tell me it.

**Comment by Natetronn** [comment]
I opened a report on rhino3dm but, thought for others who I get the following error I'd report here as well. Should I recieve an answer from them I'll report back here for others who might stumble upon this same issue when trying to install your plugin and rhino3dm.

Thanks!

```
➜  python pip3.7 install -U --user rhino3dm
Collecting rhino3dm
  Using cached https://files.pythonhosted.org/packages/2d/4d/933b108e41988ad3987e5e1545b85a639578ec30ab332086dc13170645d3/rhino3dm-0.7.1.tar.gz
Building wheels for collected packages: rhino3dm
  Building wheel for rhino3dm (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6m6xjirf/rhino3dm/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6m6xjirf/rhino3dm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-lcw499ic --python-tag cp37
       cwd: /tmp/pip-install-6m6xjirf/rhino3dm/
  Complete output (122 lines):
  /usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'long_description_content_type'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/rhino3dm
  copying src/rhino3dm/__init__.py -> build/lib.linux-x86_64-3.7/rhino3dm
  running egg_info
  writing src/rhino3dm.egg-info/PKG-INFO
  writing dependency_links to src/rhino3dm.egg-info/dependency_links.txt
  writing top-level names to src/rhino3dm.egg-info/top_level.txt
  reading manifest file 'src/rhino3dm.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.pyd' under directory 'src/rhino3dm'
  warning: no files found matching '*.so' under directory 'src/rhino3dm'
  writing manifest file 'src/rhino3dm.egg-info/SOURCES.txt'
  copying src/rhino3dm/__init__.pyi -> build/lib.linux-x86_64-3.7/rhino3dm
  copying src/rhino3dm/py.typed -> build/lib.linux-x86_64-3.7/rhino3dm
  running build_ext
  Traceback (most recent call last):
    File "/tmp/pip-install-6m6xjirf/rhino3dm/setup.py", line 32, in run
      out = subprocess.check_output(['cmake', '--version'])
    File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
      **kwargs).stdout
    File "/usr/lib/python3.7/subprocess.py", line 472, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
      restore_signals, start_new_session)
    File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'cmake': 'cmake'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-6m6xjirf/rhino3dm/setup.py", line 147, in <module>
      include_package_data=True
    File "/home/nate/.local/lib/python3.7/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-6m6xjirf/rhino3dm/setup.py", line 36, in run
      ", ".join(e.name for e in self.extensions))
  RuntimeError: CMake must be installed to build the following extensions: rhino3dm/_rhino3dm
  Error in sys.excepthook:
  Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
      from apport.fileutils import likely_packaged, get_recent_crashes
    File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
      from apport.report import Report
    File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
      import apport.fileutils
    File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
      from apport.packaging_impl import impl as packaging
    File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
      import apt
    File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
      import apt_pkg
  ModuleNotFoundError: No module named 'apt_pkg'
  
  Original exception was:
  Traceback (most recent call last):
    File "/tmp/pip-install-6m6xjirf/rhino3dm/setup.py", line 32, in run
      out = subprocess.check_output(['cmake', '--version'])
    File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
      **kwargs).stdout
    File "/usr/lib/python3.7/subprocess.py", line 472, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
      restore_signals, start_new_session)
    File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'cmake': 'cmake'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-6m6xjirf/rhino3dm/setup.py", line 147, in <module>
      include_package_data=True
    File "/home/nate/.local/lib/python3.7/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-6m6xjirf/rhino3dm/setup.py", line 36, in run
      ", ".join(e.name for e in self.extensions))
  RuntimeError: CMake must be installed to build the following extensions: rhino3dm/_rhino3dm
  ----------------------------------------
  ERROR: Failed building wheel for rhino3dm
  Running setup.py clean for rhino3dm
Failed to build rhino3dm
Installing collected packages: rhino3dm
  Running setup.py install for rhino3dm ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6m6xjirf/rhino3dm/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6m6xjirf/rhino3dm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-b33wky9_/install-record.txt --single-version-externally-managed --compile --user --prefix=
         cwd: /tmp/pip-install-6m6xjirf/rhino3dm/
    Complete output (126 lines):
    /usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/rhino3dm
    copying src/rhino3dm/__init__.py -> build/lib.linux-x86_64-3.7/rhino3dm
    running egg_info
    writing src/rhino3dm.egg-info/PKG-INFO
    writing dependency_links to src/rhino3dm.egg-info/dependency_links.txt
    writing top-level names to src/rhino3dm.egg-info/top_level.txt
    reading manifest file 'src/rhino3dm.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.pyd' under directory 'src/rhino3dm'
    warning: no files found matching '*.so' under directory 'src/rhino3dm'
    writing manifest file 'src/rhino3dm.egg-info/SOURCES.txt'
    copying src/rhino3dm/__init__.pyi -> build/lib.linux-x86_64-3.7/rhino3dm
    copying src/rhino3dm/py.typed -> build/lib.linux-x86_64-3.7/rhino3dm
    running build_ext
    Traceback (most recent call last):
      File "/tmp/pip-install-6m6xjirf/rhino3dm/setup.py", line 32, in run
        out = subprocess.check_output(['cmake', '--version'])
      File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.7/subprocess.py", line 472, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'cmake': 'cmake'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6m6xjirf/rhino3dm/setup.py", line 147, in <module>
        include_package_data=True
      File "/home/nate/.local/lib/python3.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/nate/.local/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.7/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-6m6xjirf/rhino3dm/setup.py", line 36, in run
        ", ".join(e.name for e in self.extensions))
    RuntimeError: CMake must be installed to build the following extensions: rhino3dm/_rhino3dm
    Error in sys.excepthook:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
        from apport.fileutils import likely_packaged, get_recent_crashes
      File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
        from apport.report import Report
      File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
        import apport.fileutils
      File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
        from apport.packaging_impl import impl as packaging
      File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
        import apt
      File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
        import apt_pkg
    ModuleNotFoundError: No module named 'apt_pkg'
    
    Original exception was:
    Traceback (most recent call last):
      File "/tmp/pip-install-6m6xjirf/rhino3dm/setup.py", line 32, in run
        out = subprocess.check_output(['cmake', '--version'])
      File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.7/subprocess.py", line 472, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'cmake': 'cmake'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6m6xjirf/rhino3dm/setup.py", line 147, in <module>
        include_package_data=True
      File "/home/nate/.local/lib/python3.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/nate/.local/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.7/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-6m6xjirf/rhino3dm/setup.py", line 36, in run
        ", ".join(e.name for e in self.extensions))
    RuntimeError: CMake must be installed to build the following extensions: rhino3dm/_rhino3dm
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6m6xjirf/rhino3dm/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6m6xjirf/rhino3dm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-b33wky9_/install-record.txt --single-version-externally-managed --compile --user --prefix= Check the logs for full command output.

```

**Comment by jesterKing** [comment]
You need to have CMake installed, along with necessary tools to compile (recent clang is what I tested with). The error log also mentions apt_pkg, but not sure about that. I think that is a Python module.
