### ISSUE TITLE
Failed to install PIP on v.0.4

### ISSUE THREAD

**Issue by ejnaren** [jesterKing/import_3dm#35]
**Describe the bug**
When I have the addon installed and i try and enable it the following error happens:
"
reloading addon: import_3dm 1566846073.2032914 1566846549.625186 'C:\\Users\\ejnar\\AppData\\Roaming\\Blender Foundation\\Blender\\2.80\\scripts\\addons\\import_3dm\\__init__.py'
Modules Installed () from 'C:\\Users\\ejnar\\Desktop\\import_3dm-v0.0.4.zip' into 'C:\\Users\\ejnar\\AppData\\Roaming\\Blender Foundation\\Blender\\2.80\\scripts\\addons'
Failed to load rhino3dm.
Installing pip...
Looking in links: C:\Users\ejnar\AppData\Local\Temp\tmpfa14_arn
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: 'C:\\Program Files\\Blender Foundation\\Blender\\2.80\\python\\Lib\\site-packages\\easy_install.py'
Consider using the `--user` option or check the permissions.

Traceback (most recent call last):
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\import_3dm\read3dm.py", line 78, in <module>
    import rhino3dm as r3d
ModuleNotFoundError: No module named 'rhino3dm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\import_3dm\read3dm.py", line 31, in install_dependencies
    import pip
ModuleNotFoundError: No module named 'pip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\import_3dm\read3dm.py", line 53, in install_dependencies
    raise Exception("Failed to install pip.")
Exception: Failed to install pip.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\import_3dm\__init__.py", line 43, in <module>
    from .read3dm import read_3dm
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\import_3dm\read3dm.py", line 83, in <module>
    install_dependencies()
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\import_3dm\read3dm.py", line 75, in install_dependencies
    raise Exception("Failed to install dependencies. Please make sure you have pip installed.")
Exception: Failed to install dependencies. Please make sure you have pip installed.
"

**Desktop (please complete the following information):**
System info attached:
[system-info.txt](https://github.com/jesterKing/import_3dm/files/3542566/system-info.txt)

**Comment by tsvilans** [comment]
Try running Blender with admin privileges.

**Comment by jesterKing** [comment]
I have made some changes to where and how pip gets installed. It appears to be running on my machine, so please test again with the release I'm about to create (0.0.5).

**Comment by jesterKing** [comment]
Please see release 0.0.5

**Comment by ejnaren** [comment]
You guys are heroes to jump on this so fast!
But unfortunately I still get an error. when testing the v.0.0.5.
I have tried as admin as well. Same issue.

I see there is an norwegian sentance in the following log.
Norwegian: "Systemet finner ikke angitt fil"
English: "The system cant find the file"
Following is the error log:

"
Failed to load rhino3dm, trying to install automatically...
Installing rhino3dm to C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\modules...
Traceback (most recent call last):
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\import_3dm\read3dm.py", line 113, in <module>
    import rhino3dm as r3d
ModuleNotFoundError: No module named 'rhino3dm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\import_3dm\read3dm.py", line 103, in install_dependencies
    res = sprun([pip3, "install", "--upgrade", "--target", modulespath, "rhino3dm{}".format(rhino3dm_version)])
  File "C:\Program Files\Blender Foundation\Blender\2.80\python\lib\subprocess.py", line 453, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Blender Foundation\Blender\2.80\python\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Blender Foundation\Blender\2.80\python\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Systemet finner ikke angitt fil

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\import_3dm\__init__.py", line 43, in <module>
    from .read3dm import read_3dm
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\import_3dm\read3dm.py", line 117, in <module>
    install_dependencies()
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\import_3dm\read3dm.py", line 108, in install_dependencies
    raise Exception("Failed to install dependencies. Please make sure you have pip installed.")
Exception: Failed to install dependencies. Please make sure you have pip installed. 
"

**Comment by Natetronn** [comment]
Could it be you need to install [rhino3dm](https://github.com/mcneel/rhino3dm) module?

**Comment by ejnaren** [comment]
Hmm i keep trying this out but nothing seems to work.
I have now uninstalled and reinstalled python on my machine and it now gets following error:
"
reloading addon: import_3dm 1570352588.472964 1570352617.193343 'C:\\Users\\ejnar\\AppData\\Roaming\\Blender Foundation\\Blender\\2.80\\scripts\\addons\\import_3dm\\__init__.py'
Modules Installed () from 'C:\\Users\\ejnar\\Desktop\\import_3dm-v0.0.5.zip' into 'C:\\Users\\ejnar\\AppData\\Roaming\\Blender Foundation\\Blender\\2.80\\scripts\\addons'
Failed to load rhino3dm, trying to install automatically...
Installing rhino3dm to C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\modules...
Collecting rhino3dm
  Using cached https://files.pythonhosted.org/packages/73/a3/d4a8d1044bfee9a403cfd3096bf36e986802768109728f53f05bfe9e50f3/rhino3dm-0.7.2-cp37-cp37m-win32.whl
Installing collected packages: rhino3dm
Successfully installed rhino3dm-0.7.2
You are using pip version 10.0.1, however version 19.2.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\import_3dm\read3dm.py", line 113, in <module>
    import rhino3dm as r3d
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\modules\rhino3dm\__init__.py", line 5, in <module>
    from ._rhino3dm import *
ModuleNotFoundError: No module named 'rhino3dm._rhino3dm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\import_3dm\__init__.py", line 43, in <module>
    from .read3dm import read_3dm
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\import_3dm\read3dm.py", line 121, in <module>
    raise Exception("Please restart Blender.")
Exception: Please restart Blender.
"
Restarting does not help... Any leads?

**Comment by ejnaren** [comment]
> 
> 
> Could it be you need to install [rhino3dm](https://github.com/mcneel/rhino3dm) module into Blender python?

Well now the error is a bit smaller.
It seems the addon is installed fine. And when I activate it the "modules" folder is created with rhino3dm inside. It looks alright, but still gives this error:

Traceback (most recent call last):
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\import_3dm\read3dm.py", line 113, in <module>
    import rhino3dm as r3d
ModuleNotFoundError: No module named 'rhino3dm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\import_3dm\__init__.py", line 43, in <module>
    from .read3dm import read_3dm
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\import_3dm\read3dm.py", line 121, in <module>
    raise Exception("Please restart Blender.")
Exception: Please restart Blender.

**Comment by tsvilans** [comment]
Did you try to restart Blender after that, as it says in the exception message? If the add-on is working as expected, then probably safe to ignore the issue...

Remember, your Blender Python has nothing to do with your system Python installation, so no need to re-install your system Python.

**Comment by ejnaren** [comment]
Yeah I figured it was separate python after I wrote that reply 😄 Woops.

But no it does not change after restarting.
I thought it might be because the issue started with version 0.04 and some
caching was on so I removed everything and reinstalled just to be sure.

The situation now is that when I click the private box in the add-ons
preferences I get the restart error seen above. No matter what.

I'm dying because I have the perfect project for a big client to test the
add-on 😄
Is there anything else I can try to help debug this?

søn. 6. okt. 2019, 17:23 skrev Tom Svilans <notifications@github.com>:

**Comment by ejnaren** [comment]
Hmm i just tried to remove blender completely along with all blender folders on the system and reinstall and install the addon again. Same error.

**Comment by tsvilans** [comment]
Wait... so the add-on works, but you're just getting this error message?

In the scripting window in Blender, can you type in `import rhino3dm` and tell me what is says?

Then:
- What are the contents of your `...AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\modules` folder?
- What are the contents of your `C:\Program Files\Blender Foundation\Blender\2.80\python\lib\site-packages` folder and does it contain `rhino3dm`?

If both locations contain `rhino3dm` it may be conflicting, so remove the one in the Blender Python `site-packages` folder.

If that doesn't work, move the one from the `modules` folder into the `site-packages` folder. You will probably need admin privileges. This should force the Blender Python to see it...

**Comment by ejnaren** [comment]
No. it installs but i cant activate it...
![bilde](https://user-images.githubusercontent.com/737773/66272980-0470e700-e870-11e9-9328-371cbb0d2d66.png)
Pressing this button gets the error and the box stays unchecked...

Writing the import rhino3dm command gets following:
```
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\modules\rhino3dm\__init__.py", line 5, in <module>
    from ._rhino3dm import *
ModuleNotFoundError: No module named 'rhino3dm._rhino3dm'

```
The `...AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\modules` folder:
- rhino3dm
- rhino3dm-0.7.2.dist-info

The `C:\Program Files\Blender Foundation\Blender\2.80\python\lib\site-packages` folder:
- certifi
- chardet
- idna
- numpy
- requests
- urllib3
- extern_draco.dll
- README.txt

Swapping any comination of rhino3dm folder into these folders does not change the error when trying to activate the addon.

Thanks for trying to help BTW. If we could get this working i would kiss you! (metaphorically speaking)

**Comment by tsvilans** [comment]
This is bizarre... and seems totally like a `rhino3dm` problem. 

What is in your `AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\modules\rhino3dm` folder? Should be something like:

- `__init__.py`
- `_init_.pyi`
- `_rhino3dm.cp37-win_amd64.pyd`
- `py.typed`

The third one (`_rhino3dm.cp37-win_amd64.pyd`) is the one it is looking for, I believe... 

What system are you running? Is it 64-bit? It seems like the `rhino3dm` module is not finding its own compiled components (i.e. `_rhino3dm`. For me, it runs fin with version `0.7.0`. You could try rolling back to that one?

Using something like `pip install 'rhino3dm =0.7.0' --force-reinstall`, making sure to use the `pip` that is installed with the Blender Python...

@jesterKing any ideas here?

**Comment by tsvilans** [comment]
With regard to the kissing, it is much appreciated, but I hope it won't be necessary ;)

**Comment by ejnaren** [comment]
Hmm... well the contets are as you mention above but the third file you mention is actually `_rhino3dm.cp37-win32.pyd`
But i'm running a 64bit system...
Could that be the cause?

**Comment by tsvilans** [comment]
That looks like the problem.

Is your Blender version also 32-bit? Make sure to download 64-bit Blender, 

To make sure that you are using the correct `pip`, open up the Command Prompt and use `"C:\Program Files\Blender Foundation\Blender\2.80\python\bin\python.exe" -m pip install rhino3dm` although the script should be doing this anyway...

**Comment by ejnaren** [comment]
Hmmm wierd... No its a 64bit install.
When installing rhino3dm on blender oython it gives me:
`Requirement already satisfied: rhino3dm in c:\program files\blender foundation\blender\2.80\python\lib\site-packages (0.7.2)`
So as i mentioned it seems to be doing right.
Could i force it to install `_rhino3dm.cp37-win_amd64.pyd` somehow...?

**Comment by tsvilans** [comment]
Hm... strange...

Maybe try installing the x64 `rhino3dm` version from https://pypi.org/project/rhino3dm/#files ?

**Comment by tsvilans** [comment]
You should flag this issue on the Rhino Discourse forum as well, because it seems to be related to their `rhino3dm` distribution.

**Comment by tsvilans** [comment]
Also, what does it say when you do `"C:\Program Files\Blender Foundation\Blender\2.80\python\bin\python.exe" -m pip -V` ?

**Comment by ejnaren** [comment]
> Also, what does it say when you do `"C:\Program Files\Blender Foundation\Blender\2.80\python\bin\python.exe" -m pip -V` ?

Gives: 
`pip 10.0.1 from C:\Users\ejnar\AppData\Roaming\Python\Python37\site-packages\pip (python 3.7)`

I then tried to manually install the 64bit version from the url you mentioned.
Something must have gone wrong. Now i get this:
`Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\import_3dm\__init__.py", line 43, in <module>
    from .read3dm import read_3dm
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\import_3dm\read3dm.py", line 125, in <module>
    from . import converters
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\import_3dm\converters\__init__.py", line 28, in <module>
    from .curve import import_curve
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\import_3dm\converters\curve.py", line 99, in <module>
    CONVERT[r3d.Polycurve] = import_polycurve
AttributeError: module 'rhino3dm' has no attribute 'Polycurve'
`

**Comment by ejnaren** [comment]
Alright. We are now going places here.
I changed line 99 in `...\import_3dm\converters\curve.py` from:

`CONVERT[r3d.Polycurve] = import_polycurve`
to
`CONVERT[r3d.PolyCurve] = import_polycurve`

and it seems to work now.

So it has branched into two bugs now.

One is that the rhino3dm has been installed as 32bit instead og 64 even though my system is 64.
the rhino guys might be able to answer that one best though?

The other one is probably just a typo then. Do you want a seperate bugreport for that one?

**Comment by tsvilans** [comment]
Ok, this looks like it's still somehow using your system Python / pip instead of Blender's... weird.

The second error (with `Polycurve`) suggests that you have an earlier version of the add-on. Make sure to download the latest `import_3dm` script from the repo.

**Comment by tsvilans** [comment]
No, you're using an outdated version of the add-on.

See the current code in `curve.py`: 
https://github.com/jesterKing/import_3dm/blob/master/import_3dm/converters/curve.py#L150

**Comment by ejnaren** [comment]
Ay ay ay. Thats wierd. I just downloaded it yesterday... Hold on...

**Comment by ejnaren** [comment]
Yes, just swapped it out with the files from master and it works.
This issue is all mixed up now, but thanks for the help. I'm happy. 😄
