### ISSUE TITLE
No module named 'rhino3dm

### ISSUE THREAD

**Issue by Qign** [jesterKing/import_3dm#76]
Traceback (most recent call last):
  File "D:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "D:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\import_3dm\__init__.py", line 43, in <module>
    import rhino3dm as r3d
ModuleNotFoundError: No module named 'rhino3dm'

**Comment by jesterKing** [comment]
You should install from https://github.com/jesterKing/import_3dm/releases/latest

**Comment by Mitchellja13** [comment]
Having same issue, using latest release for windows

**Comment by jesterKing** [comment]
Make sure you download the correct add-on package, install through Preferences > Add-ons, try activating it (will fail), restart Blender and ensure add-on is activate. Does that work better?

**Comment by segawasabi** [comment]
Having same issue too!  I restarted Blender, but it didn't work. 
I downloaded [import_3dm-v0.0.10-py3_10-macos-intel.zip], I think this one is the latest version, isn't it?
I'm totally new to blender,  would be appreciate if you could help me...

**Comment by pregbodan** [comment]
I'm having the same issues

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\uset\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\import_3dm\__init__.py", line 43, in <module>
    from .read3dm import read_3dm
  File "C:\Users\uset\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\import_3dm\read3dm.py", line 128, in <module>
    from . import converters
  File "C:\Users\uset\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\import_3dm\converters\__init__.py", line 23, in <module>
    import rhino3dm as r3d
  File "C:\Users\uset\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\modules\rhino3dm\__init__.py", line 5, in <module>
    from ._rhino3dm import *
ModuleNotFoundError: No module named 'rhino3dm._rhino3dm'

**Comment by pregbodan** [comment]
> You should install from https://github.com/jesterKing/import_3dm/releases/latest
i got it from this link

**Comment by eddspark** [comment]
This is because of the way the release is built. 
I'm not sure what the correct way to install the `rhino3dm` python module seperately to the `import_3dm` add-on is, but I figured out a workaround to 
I was able to fix this error by changing the directory structure of the latest release, re-zipping. and then installing. 

Did this on intel mac. 

```
unzip import_3dm-v0.0.10-py3_10-macos-intel.zip
mv modules/rhino3dm import_3dm/ 
zip -vr import_3dm_patched.zip import_3dm
```
Then I installed `import_3dm_patched.zip` using the Blender UI.

Hope that helps!

**Comment by IceKarimMore** [comment]
Hi [eddspark](https://github.com/eddspark)

Tried your solution on a PC
Unzipped
Moved "rhino3dm" subfolder (and it's files) from "modules" folder to "import_3dm" folder
(your command line "mv modules/rhino3dm import_3dm/")
Zipped again
Blender / Edit / Pref / Add ons / Install > my new zip file

I get 
"Modules Installed () from 'C:\\DATA\\AKT Architecture\\CAO\\Blender\\plugins\\free\\import_3dm-v0.0.10-py3_10-windows_corrected.zip' into 'C:\\Users\\tabba\\AppData\\Roaming\\Blender Foundation\\Blender\\3.2\\scripts\\addons'"
But no Add On called Rhino displays in the add on list ...

... 
Any one ?
An other solution ?
Correcting path in the __init__.py files ?

**Comment by boom567** [comment]
Restart blender ,and repeat install this package ,  will solve this issue.
